'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------
Namespace E5095

    Public Partial Class PdfViewer

        ''' <summary>
        ''' lbErrorMessage control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected lbErrorMessage As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' dvDocument control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected dvDocument As Global.DevExpress.Web.ASPxDataView
    End Class
End Namespace
